### ISSUE TITLE
Add travisci

### ISSUE THREAD

**Issue by harlowja** [CygnusNetworks/pypureomapi#11]
It'd be great to have a automatic CI running the unittests of this library (assuming some exist). Perhaps travis ci or other similar system?

**Comment by cygnusb** [comment]
It contains some doctests. Added travis-ci.

**Comment by harlowja** [comment]
Thanks, now I just wonder why https://travis-ci.org/CygnusNetworks/pypureomapi says its failing :-/

**Comment by cygnusb** [comment]
Already fixed. unittest was included, which does not work unter Python 2.6. Removed unittest since it is not used.
