### ISSUE TITLE
Make a 0.4 release?

### ISSUE THREAD

**Issue by harlowja** [CygnusNetworks/pypureomapi#13]

**Comment by cygnusb** [comment]
Currently testing the current master state on a production system as a final test,

**Comment by cygnusb** [comment]
Done

**Comment by harlowja** [comment]
Hmmm, did u upload to https://pypi.python.org/pypi/pypureomapi ?

**Comment by cygnusb** [comment]
I cannot since the project is claimed by some other person. I already opened up a support request on pypi to transfer the project to my account.

**Comment by cygnusb** [comment]
Is now in Debian unstable and testing.

pypi issue is still open. But the pypi uploader has been contacted, but does not have any pypi access anymore and cannot recover his password.

**Comment by harlowja** [comment]
I think u guys can open a request @ http://sourceforge.net/p/pypi/support-requests/ for that

**Comment by cygnusb** [comment]
See request #516 http://sourceforge.net/p/pypi/support-requests/516/

Opened on 07/03/2015

**Comment by cygnusb** [comment]
Got now feedback from pypi and account was transferred. I could now release 0.4 to pypi

**Comment by harlowja** [comment]
Great!
