### ISSUE TITLE
Update SOA Serial

### ISSUE THREAD

**Issue by wmturner** [CygnusNetworks/pypureomapi#17]
Hello,

I'm splitting hairs here, but per RFC 1033 we should be updating the SOA record serial number when we make changes to the zone file.  Happy to make the change if you agree.

Best,
-William

**Comment by cygnusb** [comment]
What is the relationship to the DHCP server? OMAPI is just API for DHCP, not for the nameserver.

**Comment by wmturner** [comment]
DOH :P Apologies, clicked on wrong project, please disregard.
