### ISSUE TITLE
NameError: global name 'OmapiMessage' is not defined

### ISSUE THREAD

**Issue by hughbuntu** [CygnusNetworks/pypureomapi#23]
I'm well versed in dhcpd and omapi, not so much python, so this is a noob question, sorry.

In readme.md --

When I try to use the examples (e.g. add_host_supercede_name()), I get:

"NameError: global name 'OmapiMessage' is not defined" [on msg = OmapiMessage.open("host")]

How do I define/initialize OmapiMessage correctly to get these examples to work?

**Comment by cygnusb** [comment]
That's a basic Python question. My guess is you are not importing correctly

`from pypureomapi import OmapiMessage`

should do the trick. Or:

```
import pypureomapi
...
pypureomapi.OmapiMessage
```
