### ISSUE TITLE
check_connected() unreliable.

### ISSUE THREAD

**Issue by brubbel** [CygnusNetworks/pypureomapi#26]
Killing the dhcpd process after creating the omapi object does not result in check_connected() raising an exception. A more reliable approach should employ some ping-pong test to the isc-dhcp-server, such as is done in the [wpa_supplicant control api](https://w1.fi/wpa_supplicant/devel/ctrl_iface_page.html) for example.

**Comment by cygnusb** [comment]
That is a general problem of TCP connection, which are not shutdown properly on one side. As far as I can see, there is no ping function available in the OMAPI protocol.
