### ISSUE TITLE
Please release the latest version with the last pull request

### ISSUE THREAD

**Issue by sruthirameshv** [CygnusNetworks/pypureomapi#29]
This PR : https://github.com/CygnusNetworks/pypureomapi/pull/28/files was not released or tagged into the latest version . Please bump up the version with this PR.
@cygnusb

**Comment by sruthirameshv** [comment]
Oh thats quite alright. Would you mind telling me an estimated time for the new release ?

**Comment by cygnusb** [comment]
I have done some major reorganizing of the lookup functions, cleaning up all the duplicate code and provide a better and more clean interface.
After some intensive testing I will make a release.

**Comment by cygnusb** [comment]
I don't know whether openstack uses this?!? I cannot find any reference in Openstack Neutron to pypureomapi

**Comment by sagarun** [comment]
@cygnusb We have a downstream driver at Yahoo that uses your package.

**Comment by sagarun** [comment]
@cygnusb Any updates?

**Comment by cygnusb** [comment]
Works fine here for quite some time now. But I am only using part of the functions. Have you tried the current version and find any issues?

**Comment by cygnusb** [comment]
Since I did not get any feedback and no bug reports also, I have released 0.8 now to pypi

**Comment by sagarun** [comment]
Thanks.
