### ISSUE TITLE
bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by Cody-Coleman** [CygnusNetworks/pypureomapi#33]
So I can connect using the Example with an omapi object, passing in the byted secret and key, even do things like:

`omapi..lookup_host('example1.com')`

which returns a dict just dandy with the ip, mac, and hostname. 

What I need to do is find a host record (not lease) by IP which doesn't seem to be part of the default library options (as I'm trying to find stale host records that are holding on to specific IPs and delete them) so was following the example for custom integration. When I run the: 

`r1 = omapi.query_server(m1)`

I get the `...
  File "/usr/local/lib/python3.8/site-packages/pypureomapi.py", line 183, in add_net32string
    return self.add_net32int(len(string)).add(string)
  File "/usr/local/lib/python3.8/site-packages/pypureomapi.py", line 145, in add
    self.buff.write(data)`

Stack trace. I don't understand why doing it this way is giving me this error (implying my secrets are not bytes)when I can use the same `omapi` with the lookup functions just fine. 

This is version 0.8 on python3

**Comment by Cody-Coleman** [comment]
I even see an example in Ansible for deleting a host record by IP, which is what I'm trying to do really but I don't see it in this code directly

**Comment by cygnusb** [comment]
Can you please post a complete example of code with obufscated secrets of cause. Thanks!

**Comment by Cody-Coleman** [comment]
`from pypureomapi import Omapi
from pypureomapi import OmapiMessage
omapi = Omapi('dhcpserver.place.domain.net', 7911, b'somekey', b'somesecret')
omapi.lookup_host('somehost.place.domain.net')
# GET BACK: {'ip': '192.168.4.40', 'mac': '55:54:00:80:c7:84', 'hostname': 'somehost.place.domain.net'}
m1 = OmapiMessage.open('host')
m1.update_object(dict(name="somehost.place.domain.net"))
r1 = server.query_server(m1)` 

Results in 
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/pypureomapi.py", line 1053, in query_server
    self.send_message(message)
  File "/usr/local/lib/python3.8/site-packages/pypureomapi.py", line 1044, in send_message
    self.protocol.send_message(message, sign)
  File "/usr/local/lib/python3.8/site-packages/pypureomapi.py", line 944, in send_message
    message.sign(self.authenticators[self.defauth])
  File "/usr/local/lib/python3.8/site-packages/pypureomapi.py", line 466, in sign
    self.signature = authenticator.sign(self.as_string(forsigning=True))
  File "/usr/local/lib/python3.8/site-packages/pypureomapi.py", line 457, in as_string
    self.serialize(ret, forsigning)
  File "/usr/local/lib/python3.8/site-packages/pypureomapi.py", line 442, in serialize
    outbuffer.add_bindict(self.message)
  File "/usr/local/lib/python3.8/site-packages/pypureomapi.py", line 212, in add_bindict
    self.add_net16string(key).add_net32string(value)
  File "/usr/local/lib/python3.8/site-packages/pypureomapi.py", line 183, in add_net32string
    return self.add_net32int(len(string)).add(string)
  File "/usr/local/lib/python3.8/site-packages/pypureomapi.py", line 145, in add
    self.buff.write(data)
TypeError: a bytes-like object is required, not 'str'

`

**Comment by Cody-Coleman** [comment]
Not sure if this is even the right approach to find a host record by IP, or if the DHCP server can even do this if there isn't a matching lease record, perhaps thats not possible.

**Comment by cygnusb** [comment]
This is simply a Python2/Python3 issue with utf8 and byte strings. So you are not passing the correct data types. All strings must not be unicode strings but bytestrings. That is causing the traceback.

You can only query a lease or a static defined host. As I understand, you are trying to query a host by ip. Simply use the generic function:

`omapi.lookup_by_host(ip=...)`

**Comment by Cody-Coleman** [comment]
hmm I have a record like ```host somehost.place.domain.net {
  dynamic;
  hardware ethernet 55:54:00:80:c7:84;
  fixed-address 192.168.4.40;
        supersede server.filename = "pxelinux.0";
        supersede server.next-server = c0:a8:04:64;
        supersede host-name = "somehost.place.domain.net ";
}``` And the ```omapi.lookup_by_host(ip='192.168.4.40') ``` returns pypureomapi.OmapiErrorNotFound: not found, but doing mac or name seems to work fine. Is this because of the dynamic; line for the defined host record? This is not searchable by IP?

**Comment by cygnusb** [comment]
My guess is that the combination of dynamic and fixed-address in one host statement is invalid.
Dhcpd documentation reads: The host declarations will only match a client if one of their fixed-address statements is viable on the subnet (or shared network) where the client is attached. Conversely, for a host declaration to match a client being allocated a dynamic address, it must not have any fixed-address statements. You may therefore need a mixture of host declarations for any given client...some having fixed-address statements, others without.
