### ISSUE TITLE
TabError: inconsistent use of tabs and spaces in indentation

### ISSUE THREAD

**Issue by nacolias** [CygnusNetworks/pypureomapi#39]
https://github.com/CygnusNetworks/pypureomapi/blob/79923c16a6548b962590bf1d05a5a7f51e1b26de/pypureomapi.py#L1147

Trying to import as a module and there is a tab used before this def where all others have spaces?

**Comment by nacolias** [comment]
Backwards I am, this def has leading spaces where all others are tabs

**Comment by cygnusb** [comment]
yes, thanks for reporting. Seems I have not carefully check indents on one of the merges. Fixed in 2733d21
