### ISSUE TITLE
Is it possible to add new lease with mac address?

### ISSUE THREAD

**Issue by GMasta2000** [CygnusNetworks/pypureomapi#43]
For a number of reasons, I don't want to create object with type host.
My attempts to assign a new ip address to the hardware-address have failed.
The basis of the code is taken from dev change_group
1) I open a new lease, do an IP search (10.10.0.213) and request
2) Through handle I try to update/add mac and reservation flag.
m2.update_object({b'hardware-address':pack_mac('56:6F:60:B1:01:02'),b'flags':b'0x04'})
As a result, the following is added to dhcpd.leases
lease 10.10.0.213 {
  binding state free;
  reserved;
  set remote-handle = %2;
}
And I can set and delete this flag reserved, but I can't manage the mac address.

**Comment by GMasta2000** [comment]
This is really not possible, because looking at the code of dhcpd, there is a condition for the lease object
	} else if (!omapi_ds_strcmp (name, "hardware-address")) {
	    return DHCP_R_UNCHANGED; /* XXX take change. */

**Comment by cygnusb** [comment]
Yes, that seem to be correct. Limitations on what you can do come from the OMAPI protocol itself. So if you cannot achieve this using the omshell command, it will also simply be not possible using pypureomapi.
