### ISSUE TITLE
More of a qn: Latest version not on pypi?

### ISSUE THREAD

**Issue by shraddha-pandhe** [CygnusNetworks/pypureomapi#5]
Hi,

Where do I find the pkg with latest version? Also, how do I contribute? Is there an IRC channel that I can join?

**Comment by cygnusb** [comment]
The latest version is not yet released. Please contribute by sending us pull requests, if you like to contribute features and bug fixes. There is no IRC channel which we are using.

**Comment by shraddha-pandhe** [comment]
Thanks for the explanation
