### ISSUE TITLE
Unable to update a host object: "can't update object"

### ISSUE THREAD

**Issue by shraddha-pandhe** [CygnusNetworks/pypureomapi#7]
I am using following wrapper method to update a host object:

     def update():
          try:
              o = pypureomapi.Omapi(dhcp_server_ip, port)
              m1 = pypureomapi.OmapiMessage.open("host")
              m1.update_object(dict(name=<name>))
              r1 = o.query_server(m1)
              m2 = pypureomapi.OmapiMessage.update(r1.handle))
              m2.update_object(dict(group="bar"))
              r2 = o.query_server(m2) <<<< fails here
         except pypureomapi.OmapiErrorNotFound:
              print "%s is currently not assigned" % (name,)
         except pypureomapi.OmapiError, err:
              print "an error occured: %r" % (err,)

leases database has entry:

      host <name> {
           dynamic;
           hardware ethernet <mac>;
           fixed-address <ip>;
                  supersede host-name = "<hostname>";

Error log:
message: [('result', '\x00\x00\x00\x17'), ('message', "can't update object")]
opcode: 5

**Comment by cygnusb** [comment]
This is not an issue of pypureomapi, but an error code from the OMAPI protocol. Please refer to the OMAPI documentation.

**Comment by shraddha-pandhe** [comment]
Hi @cygnusb, I am following the document [1]. Am I missing something? Still can't get it to work.

[1] https://github.com/CygnusNetworks/pypureomapi#custom-integration

**Comment by cygnusb** [comment]
I cannot help you with this issue. This is a error message coming from the DHCP server, not from the pypureomapi stack.

**Comment by mattikus** [comment]
As I just ran into this issue myself, the issue stems from the fact that you can add statements to a host entry, but you are not able to modify existing statements. You need to delete the host entry and recreate it.

Hope that helps.
