### ISSUE TITLE
Switch to using ASLv2 license?

### ISSUE THREAD

**Issue by harlowja** [CygnusNetworks/pypureomapi#9]
Hi folks @ CygnusNetworks,

A request that you may or may not be ok with (but I and others would prefer it),

`OpenStack` (http://openstack.org/) would really like to use this code in a ongoing set of work in the networking project (`Neutron` http://wiki.openstack.org/wiki/Neutron) but yet there are license incompatibilities with doing this and there is resistance to including a library that is GPLv3 licensed (due to license differences with the apache software license).

For some of the conversation/discussions/bugs about this:

- http://eavesdrop.openstack.org/irclogs/%23openstack-neutron/%23openstack-neutron.2015-06-18.log.html#t2015-06-18T15:29:45
- https://bugs.launchpad.net/neutron/+bug/1464793

There is still desire (from `spandhe` and others) to use this library as it seems to be the best out there right now, and it would be really cool if this could switch to being ASLv2 (http://www.apache.org/licenses/LICENSE-2.0) so that this could happen.

What are the thoughts about doing this? Would such a conversion be possible (seeing that the number of contributors are currently small, it would likely be easy at this stage)?

P.S. It would also have other benefits as well, more users, more eyes on this code, greater usage (and bug fixes...).

**Comment by harlowja** [comment]
Another option is to dual-license it,

I've seen this in another project I work on @ https://github.com/stackforge/cloud-init/blob/master/LICENSE

That might work to...

**Comment by cygnusb** [comment]
It would be nice to have this lib in a project like openstack to be used. Personally I do not have any objections. Let me check, if we can switch the license.

**Comment by harlowja** [comment]
Awesome, thanks much :smile:

**Comment by shraddha-pandhe** [comment]
Thats really great! Thanks @cygnusb :)

**Comment by neirbowj** [comment]
To the extent possible, I grant use of my works on this project to date under the ASLv2.

**Comment by harlowja** [comment]
Sounds great, next step I guess is to change the LICENSE in the repo (or switch it to dual-license or whatever) :+1:

**Comment by cygnusb** [comment]
There is still one contributor left, who did not yet respond to my email and give permissions to change the License, which is @zoresvit

**Comment by zoresvit** [comment]
@cygnusb and all, sorry for the delay, already replied the email. I sure don't mind the switch to Apache v2 license :) Thanks!

**Comment by cygnusb** [comment]
Thanks to all of you for your fast replies and the possibility to change the license and your contributions from the past! I have switched the license and replaced licensing information in all files. This should be sufficient to integrate it into openstack. 
I am now planing to do a 0.4 release in the coming weeks and also upload this to debian unstable. I will wait a bit to see if there is feedback coming now in from new/other contributors.

**Comment by harlowja** [comment]
Awesome I think @shraddha-pandhe wanted to submit a few pull requests and for openstack to use it there needs to be py2/py3 compatibility which I think is currently missing (see https://wiki.openstack.org/wiki/Requirements#Review_Criteria) , maybe @shraddha-pandhe can work on that as well?

**Comment by cygnusb** [comment]
I cannot see any issue on py3 compatibility. Python3 support is already there and should work, although we do not use this in production yet. Our Jenkins Job includes Python3 jenkins checks and there is no issue. Debian packaging for Python3 was missing, but I added this now.

**Comment by harlowja** [comment]
Ok then let me know if https://github.com/CygnusNetworks/pypureomapi/pulls is ok,

It'd be really nice to have https://travis-ci.org/ running the CI and posting back results to (vs some internal jenkins job?)
